Input_file:
  file_path: Files\Input_files\customer_churn.csv
  target_feature: Churn

Output_file:
  path: Files\Output_files

Preprocessing:
  Categorical_transformer: 
  - OneHotEncoder(drop='first',handle_unknown='ignore', sparse=False)
  - SelectPercentile(chi2, percentile=10)
  Numerical_trasformer: 
  - StandardScaler()


Models:
  - LogisticRegression()
  - SVC()
  - KNeighborsClassifier(n_neighbors=10)
  - DecisionTreeClassifier()
  - AdaBoostClassifier(n_estimators=100)


